version: '3.8'

services:
  # Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: creator-hub-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: creator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Ferramenta Visual para ver o Banco (Acesse http://localhost:8081)
  adminer:
    image: adminer
    container_name: creator-hub-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:
