ktor {
  deployment {
    port = 8080
  }

  application {
    modules = [ com.creatorcontenthub.ApplicationKt.module ]
  }
}

database {
  url = "jdbc:postgresql://localhost:5432/creator_db"
  user = "user"
  password = "password"
}